name: Vite Build
on:
  push:
    branches: [main]
jobs:
  build:  # 첫 번째 Job: build 작업
    runs-on: ubuntu-latest  # GitHub에서 제공하는 최신 Ubuntu 환경에서 실행
    steps:
      - uses: actions/checkout@v4  # 현재 리포지토리의 코드를 체크아웃 (clone)
      
      - run: npm ci  # 의존성 설치 (package-lock.json 기반, 빠르고 안정적)
      
      - run: npm run build  # 빌드 스크립트 실행 (보통 dist 폴더 생성됨)
      
      - uses: actions/configure-pages@v5  # GitHub Pages 배포를 위한 설정 수행
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # 아티팩트를 업로드하는 액션
        with:
          name: build-artifact # 아티팩트 이름
          path: dist
